### PR TITLE
fix: nextjs incrementalCache usage fixed

### PR DESCRIPTION
**Pull request by indatawetrust**
hi, with nextjs 10.2 version, the method of applying the incretalCache method has changed. current usage fixed

https://github.com/vercel/next.js/discussions/22384#discussioncomment-844774

### CODE REVIEW

**Comment by indatawetrust** [comment]
hi @thomvaill , do you have any comment for this pr?

**Comment by zenwork** [comment]
Is there a workaround to use this fix from this branch until the PR is merged and a new version is published? I am able clone and build but then I do not know how I should install my local build to use it

**Comment by indatawetrust** [comment]
@zenwork you can use [patch-package ](https://www.npmjs.com/package/patch-package)

**Comment by florian-hehlen** [comment]
If you are going to use patch-package please note that I got it working by using log4brains as a dev dependency rather than as a global dep. it also means that i had to wrap calls to log4brains into package.json scripts. But the good news is everything is working... even the github action to deploy to pages.

**Comment by mathiasmaerker** [comment]
@florian-hehlen How did you get it to work? I installed it localy as well and started via npm scripts but I get the same error. patching via patch-package didn't work either for me..
Any other suggestions?

**Comment by zenwork** [comment]
@mathiasmaerker , I did the following:
* installed `log4brains` and `patch-package` as a `package.json` dependencies
* run `npm install` 
* manually patch the one file in `@log4brains/web` based on this PR
* followed the `patch-package` instructions to generate the patch file
* added these scripts to the `package.json
   ``` json
  "scripts": {
    "start": "log4brains preview",
    "build": "log4brains build",
    "new": "log4brains adr new",
    "postinstall": "patch-package"
  },
   ```
* commit everything

from here on in I need to use `npm start` and `npm run new` instead of global commands

also make sure to uninstall your global installation

**Comment by mathiasmaerker** [comment]
@zenwork I tried that to, but because @log4brains is not part of the package.json you get the error `node_modules/@log4brains/web/package.json`

**Comment by zenwork** [comment]
I don't know why you would have this issue. I did not have any trouble

**Comment by mathiasmaerker** [comment]
@zenwork Well, no clue either :( but thanks a lot for your help and effort 🥇

**Comment by Sobi-WanKenobi** [comment]
@thomvaill , hopefully you are feeling better and work is lightening up a bit. Any chance you will you be able to merge this PR soon? Thanks for the work here -- really like this project a lot.

**Comment by thomvaill** [comment]
Hey thank you so much @indatawetrust, you rock!
This makes me think that we definitely need to implement https://github.com/thomvaill/log4brains/issues/77 ; that's why I updated your branch before merging by pinning the version of Nextjs to avoid this kind of issue in the future. But we definitely need to do this for all the depts. I will try to work on this next week.
Also, this issue was not caught by the scheduled non-regression tests because we only test the build and not the preview. Contributions are welcome for this, because I don't see an easy way to test this ;)

Again sorry for the delay... It's a bit difficult for me to find some time to work on the project, but hopefully your comments and contributions are really motivating, thank you for this!

**Pull request merged**
